name: ClaimSync Deployment

on:
  workflow_dispatch:

concurrency:
  group: claimsync-deployment
  cancel-in-progress: false

jobs:
  deployment:
    name: Verify Deployment Workflow
    runs-on: self-hosted

    steps:
      - name: Runner Information
        run: |
          hostname
          echo %COMPUTERNAME%
          echo %USERNAME%

      - name: Verify Deployment Workflow
        run: |
          echo "Running on self-hosted runner."